# Generated by Django 3.2.19 on 2023-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_savechats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fisrt_Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Message', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '03. Contact',
            },
        ),
    ]
