# Generated by Django 3.2.19 on 2023-06-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(choices=[('Dark', 'Dark'), ('Ligth', 'Light'), ('System Color', 'System Color')], default='Ligth', max_length=50)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '16 Theme Apparence',
            },
        ),
    ]
