# Generated by Django 3.2.19 on 2023-06-22 17:26

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_apparence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm_Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Land_Type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Farm_contact_Email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Farm_contact_phone', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('total_area', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('district', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Farm_logo', models.ImageField(blank=True, default='app/image/profile_DP_def.jpg', max_length=255, null=True, upload_to='app/image')),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '04. Farms',
            },
        ),
        migrations.AlterModelOptions(
            name='apparence',
            options={'verbose_name_plural': '30. Theme Apparence'},
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_Name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Plot_Number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Plot_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('features_geometry', models.TextField()),
                ('features_geometry_color', colorfield.fields.ColorField(blank=True, default='#000000', help_text='#000000', image_field=None, max_length=100, samples=None)),
                ('Available_Status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Booked', 'Booked'), ('Sold', 'Sold'), ('Cancelled', 'Cancelled')], default='Available', max_length=100, null=True)),
                ('Plot_Face', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Plot_Area_in_sqft', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Price', models.FloatField(default=0)),
                ('Currency_Symbol', models.CharField(blank=True, choices=[('$', '$'), ('€', '€'), ('£', '£'), ('Rs', 'Rs')], default='Rs', max_length=50, null=True)),
                ('Booked_Date', models.DateField()),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive')], default='Deactive', max_length=50)),
                ('Created_Date', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farm')),
            ],
            options={
                'verbose_name_plural': '05. Plots',
            },
        ),
    ]
