# Generated by Django 3.2.19 on 2023-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230622_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='Booked_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
