# Generated by Django 3.2.19 on 2023-07-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230622_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='Number_of_trees',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
