# Generated by Django 3.2.19 on 2023-07-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_farm_visits_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='Visits_Status',
        ),
    ]
