# Generated by Django 3.2.19 on 2023-07-03 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_remove_farm_visits_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Live_streaming_via', models.CharField(choices=[('Drone 1', 'Drone 1'), ('Drone 2', 'Drone 2'), ('Drone 3', 'Drone 3'), ('Camera 1', 'Camera 1')], default='Drone 1', max_length=255)),
                ('Full_Name', models.CharField(default='', max_length=255)),
                ('Phone_Number', models.CharField(default='', max_length=12)),
                ('Email', models.CharField(default='', max_length=255)),
                ('Start_Appointment_Date', models.DateTimeField()),
                ('End_Appointment_Date', models.DateTimeField()),
                ('Address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('City', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('State', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Post_Code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Confirmation', models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone')], default='Email', max_length=255)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Reject', 'Reject'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.farm')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '06. Appointment',
            },
        ),
    ]
