# Generated by Django 3.2.19 on 2023-07-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230705_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Email_Send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255),
        ),
    ]
