# Generated by Django 3.2.19 on 2023-07-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_appointment_email_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Email_Send',
        ),
    ]
