# Generated by Django 3.2.19 on 2023-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_appointment_email_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Address',
            field=models.TextField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
